CREATE TABLE `share_links` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`shareCode` varchar(50) NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`studentIds` text,
	`expiresAt` timestamp,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `share_links_id` PRIMARY KEY(`id`),
	CONSTRAINT `share_links_shareCode_unique` UNIQUE(`shareCode`)
);
--> statement-breakpoint
CREATE TABLE `student_score_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`grade` varchar(50),
	`class` varchar(100),
	`school` varchar(255),
	`gender` enum('男','女') NOT NULL,
	`longrun` int,
	`swim` int,
	`long100` int,
	`longContrib` varchar(50),
	`football` int,
	`basketball` int,
	`volleyball` int,
	`ballContrib` varchar(50),
	`run50` int,
	`situp` int,
	`ball` int,
	`rope` int,
	`pullup` int,
	`jump` int,
	`selectContrib` varchar(50),
	`selectedProjects` text,
	`total40` varchar(50),
	`status` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `student_score_data_id` PRIMARY KEY(`id`)
);
